defmodule Groove.Repo.Migrations.AddProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profiles, primary_key: false) do
      add :id,
          references(:users, column: :id, name: "profiles_id_fkey", type: :uuid, prefix: "public"),
          primary_key: true,
          null: false

      add :name, :text, null: false
    end
  end

  def down do
    drop constraint(:profiles, "profiles_id_fkey")

    drop table(:profiles)
  end
end