defmodule Groove.Repo.Migrations.AddFeatures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:features, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :points, :bigint, default: 0
      add :status, :text, default: "new"
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :sprint_id,
          references(:sprints,
            column: :id,
            name: "features_sprint_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:features, ["status"])
  end

  def down do
    drop constraint(:features, "features_sprint_id_fkey")

    drop_if_exists index(:features, ["status"], name: "features_status_index")

    drop table(:features)
  end
end